// setting up a variable named authorsName with a value of "William Doane"
//
var authorsName = "William Doane";

// setting up a fuction called rollDie that works by using the random function that generates a random number x, where 0 <= x < 1, which is then multiplied by 6 and rounded down. The end result is a number between 0 and 5. Finally, 1 is added so that our range becomes 1 to 6, just like a six sided die.
//
var rollDie = function () {
  return Math.floor(Math.random() * 6) + 1;
};

// setting up a variable that returns a prompt: Guess a number from 1 to 6.
//
var getUserGuess = function () {
  return prompt("Guess a number from 1 to 6");
};

// takes the variable getUserGuess and converts it from a string to a decimal integer using the parseInt command. 
//
var convertToDecimal = function (str) {
  return parseInt(str, 10);
};

// creates a function called isWinner that checks to see if num and guess are equal to each other. if they are then it returns true else it returns false.
//
var isWinner = function (num, guess) {
  if (num === guess) {
   return true;
  } else {
   return false;
  }
};

// creates a function called main.
//
var main = function () {

// creates two variables, one called num and one called guess.
//  
  var num, guess;

// setting the variable num equal to the number generated by rollDie. 
//
  num = rollDie();

// setting the variable guess equal to the value of getUserGuess.
//
  guess = getUserGuess();

// converts the value of guess from a string to a decimal number.
//  
  guess = convertToDecimal(guess);

// setting up an if loop that checks to see if num and guess are equal to each other. If they are equal, it creates an alert that tells you that you have won.
//  
  if ( isWinner(num, guess) ) {
    alert("You win!");

// else, it creates an alert that tells you that you were wrong, and what the correct number was.
//  
  } else {
    alert("Sorry. The answer was: " + num);
  }
  
};